tf

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -8,67 +8,84 @@ on:
 env:
   AWS_REGION: ${{ secrets.AWS_REGION }}
   ECR_REPOSITORY: operation-stacked-workout
+  MAJOR_VERSION: 0 # Fixed Major Version
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout workout-app code
-      uses: actions/checkout@v2
+      - name: Checkout workout-app code
+        uses: actions/checkout@v2
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v1
-      env:
-        AWS_REGION: ${{ secrets.AWS_REGION }}
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        push: true
-        tags: ${{ steps.login-ecr.outputs.registry }}/operation-stacked-workout:latest
+      - name: Generate version number
+        run: echo "APP_VERSION=${{ env.MAJOR_VERSION }}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
 
-    - name: Update container-service.json with the new image
-      run: |
-        # Update the container-service.json file with the new image URL for workout-container
-        # You can use a tool like jq or a script to perform the update
+      - name: Store version in S3
+        run: echo ${{ env.APP_VERSION }} | aws s3 cp - s3://${{ secrets.OPERATION_STACKED_WORKOUT_VERSION_BUCKET }}/${{ env.APP_VERSION }}
 
-    - name: Set AWS credentials as environment variables
-      run: |
-        echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
-        echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
-        echo "export AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          push: true
+          tags: ${{ steps.login-ecr.outputs.registry }}/operation-stacked-workout:${{ env.APP_VERSION }}
+          build-args: VERSION=${{ env.APP_VERSION }}
 
-    - name: SSH into EC2 and deploy new container
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USERNAME }}
-        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
-        script: |
-    
-          # Log in to Amazon ECR
-          sudo $(aws ecr get-login --no-include-email --region $AWS_REGION)
 
-          # Stop and remove the existing container
-          sudo docker stop operation-stacked-workout
-          sudo docker rm operation-stacked-workout
+      - name: Set AWS credentials as environment variables
+        run: |
+          echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+          echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          echo "export AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
 
-          # Pull the latest image from ECR
-          sudo docker pull ${{ secrets.ECR_URL }}/operation-stacked-workout:latest
-
-          # Start the new container
+      - name: SSH into EC2 and deploy new container
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
+          script: |
+            # Log in to Amazon ECR
+            sudo $(aws ecr get-login --no-include-email --region $AWS_REGION)
+            
+            # Stop and remove the existing container
+            sudo docker stop operation-stacked-workout
+            sudo docker rm operation-stacked-workout
+            
+            # Pull the latest image from ECR
+            sudo docker pull ${{ secrets.ECR_URL }}/operation-stacked-workout:${{ env.APP_VERSION }}
+            
+            # Start the new container
             sudo docker run -d -p 5002:8080 \
-            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
-            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
-            -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
-            --name operation-stacked-workout \
-            ${{ secrets.ECR_URL }}/operation-stacked-workout:latest
-          
+              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
+              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
+              -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
+              --name operation-stacked-workout \
+              ${{ secrets.ECR_URL }}/operation-stacked-workout:${{ env.APP_VERSION }}
+
+      # Validate deployment
+      - name: Validate deployment
+        run: |
+          for i in {1..60}; do  # 60 attempts * 3 seconds sleep = 180 seconds (3 minutes)
+            echo "Checking if the deployed version is ${APP_VERSION} (Attempt $i)"
+            DEPLOYED_VERSION=$(curl --silent https://app.operationstacked.com/workout/version/latest)
+            if [ "$DEPLOYED_VERSION" = "${{ env.APP_VERSION }}" ]; then
+              echo "Deployment validation succeeded"
+              exit 0
+            fi
+            sleep 3
+          done
+          echo "Deployment validation failed"
+          exit 1
